name: Upload video

on:
  push:
    branches: [ main ]

jobs:
  upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v1

    - name: Setup tools.cli 
      uses: DeLaGuardo/setup-clojure@3.7
      with:
        cli: 1.10.3.1075

    - name: Install dependencies
      run: clojure -M:deps
      shell: bash
    
    - name: Check vulnerable code
      uses: clj-holmes/clj-holmes-action@main
      with:
        output-type: 'stdout'
        fail-on-result: 'true'
        
    - name: Check vulnerable dependencies
      run: $ clojure -Sdeps '{:deps {io.github.clj-holmes/clj-watson {:git/tag "v3.0.0" :git/sha "b93c486"}}}' -M -m clj-watson.cli scan -p deps.edn -a clojure-lsp -f -s -t github-advisory

      
    - name: Create video
      env:
        VOICE_RSS_KEY: ${{ secrets.VOICE_RSS_KEY }}
        X_RAPIDAPI_HOST: ${{ secrets.X_RAPIDAPI_HOST }}
        X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
      run: clojure -M -m news2video.main
